name: Analyze PowerShell

on: push

permissions:
  security-events: write  # Required to upload SARIF results

jobs:
  analyze-powershell-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Run PSScriptAnalyzer
      uses: microsoft/psscriptanalyzer-action@main
      with:
        path: .\
        recurse: true 
        output: results.sarif

    - name: Upload PowerShell SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: PSScriptAnalyzer