name: Pester Unit Test

on: push

jobs:
    pester-test:
      name: Pester test
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: Perform a Pester test from the Tests.ps1 file
          shell: pwsh
          run: |
            ./Run-ScepmanTests.ps1